version: "3.8"

services:
  frontend:
    build:
      context: ./frontend # Path to your frontend directory
    image: audio-app-frontend # Name of the image after building
    environment:
      - REACT_APP_API_URL=http://backend:5000 # Set environment variable
    ports:
      - "3000:3000"
    depends_on:
      - backend # Ensure backend is started before frontend

  backend:
    build:
      context: ./backend # Path to your backend directory
    image: audio-app-backend # Name of the image after building
    ports:
      - "5000:5000"
