version: "3.8"

services:
  backend:
    image: my-backend # Use the built backend image
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET_KEY=your-secret-key # Set your secret key
    restart: "no" # Ensure it doesn't restart automatically

  frontend:
    image: my-frontend # Use the built frontend image
    ports:
      - "3000:3000"
    restart: "no" # Ensure it doesn't restart automatically
