version: "3.8"

services:
  backend:
    image: jchkiyo/audio-app-backend:latest # Use the pre-built Flask backend image
    ports:
      - "${BACKEND_PORT:-5000}:5000" # Use the environment variable BACKEND_PORT or default to 5000
    networks:
      - audio-network
    environment:
      - JWT_SECRET_KEY=your-secret-key # Set environment variables as needed

  frontend:
    image: jchkiyo/audio-app-frontend:latest # Use the pre-built React frontend image
    ports:
      - "${FRONTEND_PORT:-3000}:3000" # Use the environment variable FRONTEND_PORT or default to 3000
    networks:
      - audio-network

networks:
  audio-network:
    driver: bridge # Use a bridge network for communication between services
