version: "3.8"

services:
  backend:
    image: jchkiyo/audio-app-backend:latest # Use the pulled backend image
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET_KEY=your-secret-key # Set your secret key
    restart: "no" # Ensure it doesn't restart automatically

  frontend:
    image: jchkiyo/audio-app-frontend:latest # Use the pulled frontend image
    ports:
      - "3000:3000"
    restart: "no" # Ensure it doesn't restart automatically
