version: "3.8"

services:
  backend:
    image: jchkiyo/audio-app-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-50000}:50000"
    networks:
      - audio-network

  frontend:
    image: jchkiyo/audio-app-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:50000} # Pass REACT_APP_API_URL as a build argument
    ports:
      - "${FRONTEND_PORT:-30000}:30000"
    networks:
      - audio-network
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:50000} # Environment variable for runtime

networks:
  audio-network:
    driver: bridge
