version: "3.8"

services:
  backend:
    image: jchkiyo/audio-app-backend:latest # Use the pre-built Flask backend image
    ports:
      - "5000:5000" # Expose port 5000 for the Flask app
    networks:
      - audio-network
    environment:
      - JWT_SECRET_KEY=your-secret-key # Set environment variables as needed

  frontend:
    image: jchkiyo/audio-app-frontend:latest # Use the pre-built React frontend image
    ports:
      - "3000:3000" # Expose port 3000 for the React app
    networks:
      - audio-network

networks:
  audio-network:
    driver: bridge # Use a bridge network for communication between services
